### ISSUE TITLE
App name...

### ISSUE THREAD

**Issue by Gabriele69** [Ruditimmermans/sailbook#1]
Yes I know, it's a stupid question, but can you rename the app with something like "Ubook" or similar. Saill... sound too much like the original Sailfish app... :-)
in any case, the icon with the sailor is very pretty.
My compliments. It's a very nice and useful app !
g

**Comment by Ruditimmermans** [comment]
Hi,
I´m the orginal coder of Sailbook on Sailfish OS indeed, and i like to keep the name also on Ubuntu Touch becoss for me its a good name.... The icon should be fixed by now and next week i release v1.2 with more option....

Greetings,

Rudi
