### ISSUE TITLE
New Top Bar, missing group

### ISSUE THREAD

**Issue by Gabriele69** [Ruditimmermans/sailbook#2]
Hello, first of all, thanks a lot for the work you are doing with this app.
The new bar is very nice and functional, but does not allow access to groups. 
In the previous FB bar it was possible to access the groups from the sandich menu at the top right. 
Now I can not find a way to access to the groups.
I do not know if it is possible to update the new bar for this.
GM

**Comment by Ruditimmermans** [comment]
Hi this woul be fixed into the new update ;)
