### ISSUE TITLE
 (Groups) missing the button to publish

### ISSUE THREAD

**Issue by Gabriele69** [Ruditimmermans/sailbook#3]
Hi Rudi.

Thank you for adding the ability to access groups from the top bar.
I point out that entering the group and clicking on the button to publish, missing the button to publish after typing something in the window.

**Comment by Gabriele69** [comment]
this is the window that opens (in the group) to publish something. As you can see, you can write, but the button to publish is missing
![photo_2018-01-26_15-04-38](https://user-images.githubusercontent.com/17642335/35443135-3ff1a358-02aa-11e8-9974-0324e0bf348c.jpg)

**Comment by Ruditimmermans** [comment]
Ok thanks for let me know, can you please send me a email on rudi.timmer@gmx.us so i can send you a test version it seems Facebook blocks some thing so i need to move the bar under the page... thanks!

**Comment by Gabriele69** [comment]
Hi Rudi.
I send you an email.
BR
Gabriele

**Comment by Gabriele69** [comment]
Hi Rudi. Why your beautiful app is'nt on Open Store?

Gabriele
